// NetworkX-compatible Graph Data Model for QuantumForce Urban Traffic Network

export const INITIAL_INTERSECTIONS = {
  I1: {
    id: 'I1',
    name: 'Cyber Central North',
    x: 200,
    y: 150,
    density: 72,
    queue: 24,
    capacity: 85,
    signal: 'RED',
    signalDuration: 45,
    optimizedSignal: 'GREEN',
    optimizedDuration: 65,
    connectedTo: ['I2', 'I3'],
    lanes: 4,
    incomingVehicles: 18,
    outgoingVehicles: 14,
    avgWaitTime: 52, // seconds
    phase: 'North-South Green / East-West Red',
  },
  I2: {
    id: 'I2',
    name: 'Nexus Hub East',
    x: 520,
    y: 140,
    density: 48,
    queue: 14,
    capacity: 62,
    signal: 'GREEN',
    signalDuration: 60,
    optimizedSignal: 'GREEN',
    optimizedDuration: 55,
    connectedTo: ['I1', 'I4', 'I5'],
    lanes: 4,
    incomingVehicles: 12,
    outgoingVehicles: 15,
    avgWaitTime: 28,
    phase: 'All-Phase Adaptive',
  },
  I3: {
    id: 'I3',
    name: 'Quantum Plaza West',
    x: 180,
    y: 400,
    density: 91,
    queue: 51,
    capacity: 96,
    signal: 'RED',
    signalDuration: 50,
    optimizedSignal: 'GREEN',
    optimizedDuration: 75,
    connectedTo: ['I1', 'I4'],
    lanes: 3,
    incomingVehicles: 28,
    outgoingVehicles: 8,
    avgWaitTime: 78,
    phase: 'Heavy Congestion Queue Lock',
  },
  I4: {
    id: 'I4',
    name: 'Vertex Core South',
    x: 500,
    y: 410,
    density: 63,
    queue: 29,
    capacity: 74,
    signal: 'YELLOW',
    signalDuration: 5,
    optimizedSignal: 'GREEN',
    optimizedDuration: 60,
    connectedTo: ['I2', 'I3', 'I6', 'HOSPITAL'],
    lanes: 6,
    incomingVehicles: 22,
    outgoingVehicles: 19,
    avgWaitTime: 46,
    phase: 'Transit Corridor Switch',
  },
  I5: {
    id: 'I5',
    name: 'Synapse Junction Mid',
    x: 780,
    y: 200,
    density: 37,
    queue: 9,
    capacity: 48,
    signal: 'GREEN',
    signalDuration: 55,
    optimizedSignal: 'GREEN',
    optimizedDuration: 45,
    connectedTo: ['I2', 'I6'],
    lanes: 3,
    incomingVehicles: 8,
    outgoingVehicles: 11,
    avgWaitTime: 22,
    phase: 'Free Flow East Arterial',
  },
  I6: {
    id: 'I6',
    name: 'Hyperion Cross SouthEast',
    x: 800,
    y: 450,
    density: 55,
    queue: 18,
    capacity: 67,
    signal: 'GREEN',
    signalDuration: 40,
    optimizedSignal: 'YELLOW',
    optimizedDuration: 30,
    connectedTo: ['I4', 'I5'],
    lanes: 4,
    incomingVehicles: 15,
    outgoingVehicles: 14,
    avgWaitTime: 36,
    phase: 'Harbor Link Balancing',
  },
  HOSPITAL: {
    id: 'HOSPITAL',
    name: 'City General Hospital (Emergency Hub)',
    x: 350,
    y: 530,
    density: 20,
    queue: 2,
    capacity: 30,
    signal: 'GREEN',
    signalDuration: 90,
    optimizedSignal: 'GREEN',
    optimizedDuration: 90,
    connectedTo: ['I4'],
    lanes: 2,
    isHospital: true,
  },
};

export const INITIAL_ROADS = [
  { id: 'R1', from: 'I1', to: 'I2', name: 'Central Express Blvd', capacity: 1800, speedLimit: 60, congestion: 'medium' },
  { id: 'R2', from: 'I1', to: 'I3', name: 'West Corridor Pkwy', capacity: 1400, speedLimit: 50, congestion: 'high' },
  { id: 'R3', from: 'I2', to: 'I4', name: 'Cross-Town Ave', capacity: 2000, speedLimit: 50, congestion: 'medium' },
  { id: 'R4', from: 'I2', to: 'I5', name: 'East Ring Highway', capacity: 2400, speedLimit: 80, congestion: 'low' },
  { id: 'R5', from: 'I3', to: 'I4', name: 'South Valley Way', capacity: 1600, speedLimit: 50, congestion: 'high' },
  { id: 'R6', from: 'I5', to: 'I6', name: 'Harbor Link Road', capacity: 1800, speedLimit: 60, congestion: 'low' },
  { id: 'R7', from: 'I4', to: 'I6', name: 'Metro South Transit', capacity: 2200, speedLimit: 60, congestion: 'medium' },
  { id: 'R8', from: 'I4', to: 'HOSPITAL', name: 'Hospital Emergency Access', capacity: 1200, speedLimit: 40, congestion: 'low' },
];

export const EMERGENCY_ROUTE = ['I1', 'I2', 'I5', 'I4', 'HOSPITAL'];
